name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
      S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
      BLUESKY_APPPASSWORD: ${{ secrets.BLUESKY_APPPASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - name: Update
        run: yarn update-tweets
